apiVersion: apps/v1
kind: Deployment
metadata:
  name: reactapp-deployment
  namespace: k8react
  labels:
    app: reactapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reactapp
  template:
    metadata:
      labels:
        app: reactapp
    spec:
      containers:
      - name: reactapp
        imagePullPolicy: Always
        image: eastyler/myapp:works 
        ports:
        - containerPort: 3001
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: reactapp-service
#   namespace: k8react
# spec:
#   type: NodePort
#   selector:
#     app: reactapp
#   ports:
#     - protocol: TCP
#       port: 3001
#       targetPort: 3001
#       nodePort: 30500
